// announcement.rs — read RELEASES.json bundled into the .app as a resource.
//
// The file is a single source of truth shared between the GitHub Release
// description, the in-app "What's New" modal, and (eventually) the updater
// manifest's `notes` field generated by release.sh.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use tauri::{AppHandle, Manager};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ReleaseEntry {
    pub version: String,
    pub date: String,
    pub title: String,
    #[serde(default)]
    pub highlights: Vec<String>,
    #[serde(default)]
    pub notes: String,
}

/// Resolve the bundled RELEASES.json path. Falls back to walking up from
/// the dev executable for `cargo tauri dev`.
fn releases_path(app: &AppHandle) -> Option<PathBuf> {
    // Production: bundled resource at .app/Contents/Resources/_up_/_up_/_up_/RELEASES.json
    if let Ok(resource_dir) = app.path().resource_dir() {
        // Tauri's resources["../../../RELEASES.json"] flattens the relative
        // path into the bundle's Resources/ — find any RELEASES.json under it.
        let direct = resource_dir.join("RELEASES.json");
        if direct.exists() { return Some(direct); }
        // Walk up: some Tauri versions preserve the relative depth instead.
        for entry in walkdir::WalkDir::new(&resource_dir).max_depth(6).into_iter().flatten() {
            if entry.file_name() == "RELEASES.json" {
                return Some(entry.path().to_path_buf());
            }
        }
    }
    // Dev: walk up from CWD until we find RELEASES.json at the repo root.
    let mut cur = std::env::current_dir().ok()?;
    for _ in 0..6 {
        let candidate = cur.join("RELEASES.json");
        if candidate.exists() { return Some(candidate); }
        cur = cur.parent()?.to_path_buf();
    }
    None
}

pub fn load(app: &AppHandle) -> Result<Vec<ReleaseEntry>, String> {
    let path = releases_path(app)
        .ok_or_else(|| "RELEASES.json not found".to_string())?;
    let raw = std::fs::read_to_string(&path).map_err(|e| e.to_string())?;
    serde_json::from_str(&raw).map_err(|e| format!("RELEASES.json parse: {e}"))
}
